steps:
 - name: 'gcr.io/cloud-builders/docker:18.06.1'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/uppy-companion:latest || exit 0
 - name: 'gcr.io/cloud-builders/docker:18.06.1'
   args: [
     'build',
     '-t', 'gcr.io/$PROJECT_ID/uppy-companion:$SHORT_SHA',
     '--cache-from', 'gcr.io/$PROJECT_ID/uppy-companion:latest',
     '-f', './packages/@uppy/companion/Dockerfile',
     './packages/@uppy/companion/' ]
 - name: 'gcr.io/cloud-builders/docker:18.06.1'
   args: ['push', 'gcr.io/$PROJECT_ID/uppy-companion:$SHORT_SHA']
timeout: 1800s
